# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

moPMR_individual_Egger <- function(xin, Yin, Zxin, Zyin, gammain, alphain, max_iterin, epsin) {
    .Call(`_moPMR_moPMR_individual_Egger`, xin, Yin, Zxin, Zyin, gammain, alphain, max_iterin, epsin)
}

moPMR_summary_Egger <- function(betaxin, betayin, Sigma1sin, Sigma2sin, Sigmayin, samplen1, samplen2, gammain, alphain, max_iterin, epsin) {
    .Call(`_moPMR_moPMR_summary_Egger`, betaxin, betayin, Sigma1sin, Sigma2sin, Sigmayin, samplen1, samplen2, gammain, alphain, max_iterin, epsin)
}

